# Generated by Django 5.2 on 2025-08-06 08:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='学習したこと（マークダウン形式）')),
                ('instruction_text', models.TextField(blank=True, null=True, verbose_name='想定される質問例')),
                ('output_text', models.TextField(blank=True, null=True, verbose_name='質問への回答例')),
                ('subject', models.CharField(max_length=100, verbose_name='科目名')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('lesson_date', models.DateField(default=django.utils.timezone.now, verbose_name='授業日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('tags', models.ManyToManyField(blank=True, to='memo_app.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '学習メモ',
                'verbose_name_plural': '学習メモ',
                'ordering': ['-lesson_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='memo_attachments/', verbose_name='添付ファイル')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='ファイルの説明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='memo_app.learningmemo', verbose_name='学習メモ')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
