# Generated by Django 5.2 on 2025-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmemo',
            name='record_type',
            field=models.CharField(choices=[('memo', '学習メモ'), ('conversation', 'AIとの対話記録')], default='memo', max_length=20, verbose_name='記録の種別'),
        ),
        migrations.AlterField(
            model_name='learningmemo',
            name='input_text',
            field=models.TextField(verbose_name='記録内容（マークダウン形式）'),
        ),
    ]
