# Generated by Django 5.2 on 2025-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0002_learningmemo_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmemo',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='単元'),
        ),
    ]
