# docker-compose.prod.yml

services:
  nginx:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: