# Generated by Django 5.2 on 2025-08-06 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='評価日時')),
                ('question', models.TextField(verbose_name='質問文 (RAGAS: question)')),
                ('ground_truth', models.TextField(blank=True, null=True, verbose_name='質問に対する想定回答文 (RAGAS: ground_truth)')),
                ('actual_answer', models.TextField(verbose_name='実際の回答文 (RAGAS: answer)')),
                ('faithfulness_score', models.FloatField(blank=True, null=True, verbose_name='Faithfulness スコア')),
                ('answer_relevancy_score', models.FloatField(blank=True, null=True, verbose_name='Answer Relevancy スコア')),
                ('context_precision_score', models.FloatField(blank=True, null=True, verbose_name='Context Precision スコア')),
                ('context_recall_score', models.FloatField(blank=True, null=True, verbose_name='Context Recall スコア')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考（評価プロセスや課題など）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ログ作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='評価者')),
            ],
            options={
                'verbose_name': 'RAG評価ログ',
                'verbose_name_plural': 'RAG評価ログ',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
