# Generated by Django 5.2 on 2025-08-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memo_app', '0001_initial'),
        ('rag_app', '0001_initial'),
        ('rag_config_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragevaluation',
            name='rag_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rag_config_log.ragconfiguration', verbose_name='RAG構成'),
        ),
        migrations.AddField(
            model_name='ragevaluation',
            name='related_memos_as_context',
            field=models.ManyToManyField(blank=True, to='memo_app.learningmemo', verbose_name='RAGに用いた学習メモ (RAGAS: context)'),
        ),
    ]
