# Generated by Django 5.2 on 2025-08-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memo_app', '0003_learningmemo_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='期限日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='memo_app.learningmemo', verbose_name='関連学習メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDo',
                'ordering': ['-created_at'],
            },
        ),
    ]
