# Generated by Django 5.2 on 2025-08-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0003_learningmemo_unit'),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='memo_app.learningmemo', verbose_name='関連学習メモ'),
        ),
    ]
