# Generated by Django 5.2 on 2025-08-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memo_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200, unique=True, verbose_name='RAG構成名 (ユニークな識別子)')),
                ('rag_model_name', models.CharField(max_length=200, verbose_name='RAGに使ったLLM')),
                ('rag_model_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='RAGに使ったLLMバージョン')),
                ('embedding_model_name', models.CharField(max_length=200, verbose_name='RAGに使ったEmbeddingモデル')),
                ('embedding_model_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Embeddingモデルバージョン')),
                ('rag_tool_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='RAGツール名 (例: Dify, Langflow)')),
                ('rag_tool_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='RAGツールバージョン')),
                ('rag_type', models.CharField(choices=[('Standard', 'Standard RAG (Retrieval-Augmented Generation)'), ('Graph', 'GraphRAG'), ('HyDE', 'HyDE (Hypothetical Document Embeddings)'), ('Multi-hop', 'Multi-hop RAG'), ('Fusion', 'Fusion RAG (e.g., RRF)'), ('Agentic', 'Agentic RAG'), ('Other', 'その他')], default='Standard', max_length=50, verbose_name='RAGの種類')),
                ('rag_workflow_file', models.FileField(blank=True, null=True, upload_to='rag_workflows/', verbose_name='ワークフローファイル (.json, .yamlなど)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='RAG構成の詳細説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('used_memos', models.ManyToManyField(blank=True, related_name='rag_configs', to='memo_app.learningmemo', verbose_name='使用した学習メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'RAG構成ログ',
                'verbose_name_plural': 'RAG構成ログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
