# Generated by Django 5.2 on 2025-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_config_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragconfiguration',
            name='config_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='AIエージェント構成名 (ユニークな識別子)'),
        ),
        migrations.AlterField(
            model_name='ragconfiguration',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='AIエージェント構成の詳細説明'),
        ),
        migrations.AlterField(
            model_name='ragconfiguration',
            name='embedding_model_name',
            field=models.CharField(max_length=200, verbose_name='Embeddingモデル'),
        ),
        migrations.AlterField(
            model_name='ragconfiguration',
            name='rag_model_name',
            field=models.CharField(max_length=200, verbose_name='LLM名'),
        ),
        migrations.AlterField(
            model_name='ragconfiguration',
            name='rag_model_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LLMバージョン'),
        ),
        migrations.AlterField(
            model_name='ragconfiguration',
            name='rag_tool_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ツール名 (例: Dify, Langflow)'),
        ),
        migrations.AlterField(
            model_name='ragconfiguration',
            name='rag_tool_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ツールバージョン'),
        ),
    ]
