# Generated by Django 5.2 on 2025-08-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_config_log', '0002_alter_ragconfiguration_config_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ragconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'AIエージェント構成ログ', 'verbose_name_plural': 'AIエージェント構成ログ'},
        ),
    ]
