# Generated by Django 5.2 on 2025-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_config_log', '0003_alter_ragconfiguration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragconfiguration',
            name='rag_type',
            field=models.CharField(choices=[('Standard', 'Standard RAG (Retrieval-Augmented Generation)'), ('Graph', 'GraphRAG'), ('HyDE', 'HyDE (Hypothetical Document Embeddings)'), ('Multi-hop', 'Multi-hop RAG'), ('Fusion', 'Fusion RAG (e.g., RRF)'), ('Agentic', 'Agentic RAG'), ('Other', 'その他'), ('none', 'RAG未使用')], default='Standard', max_length=50, verbose_name='RAGの種類'),
        ),
    ]
