# Generated by Django 5.2 on 2025-08-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_config_log', '0004_alter_ragconfiguration_rag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragconfiguration',
            name='based_on_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_configs', to='rag_config_log.ragconfiguration', verbose_name='見本にした構成'),
        ),
    ]
